### ISSUE TITLE
API Documentation error for transcript/{asset-name}/

### ISSUE THREAD

**Issue by foo4thought** [WGBH/FixIt#18]
Amend from:

```A single transcript can be retrieved by appending the asset name, e.g. /api/transcript/cpb-aacip_500-xp6v2q58/.```
to 
```A single transcript can be retrieved by appending the asset name and /corrected/, e.g. /api/transcript/cpb-aacip_500-xp6v2q58/corrected/.```

**Comment by eyemyth** [comment]
I just went ahead and restored the endpoint described here - it was as easy to do that as to fix the docs.
