### ISSUE TITLE
Error message on FIX IT Facebook login

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH/FixIt#19]
I am getting the following error when I try to use FIX IT and login via Facebook:

<img width="1416" alt="screen shot 2019-02-07 at 1 35 10 pm" src="https://user-images.githubusercontent.com/5992135/52434450-55f88480-2add-11e9-8ec6-8592e5260d18.png">

**Comment by eyemyth** [comment]
It's because FB changed their rules to require SSL for callback URLs. I can fix it by adding a certificate.

**Comment by caseyedavis12** [comment]
@eyemyth, thanks for the quick response. Adding a certificate to fix the issue would be much appreciated.

**Comment by eyemyth** [comment]
Should be working now.
